#!/bin/sh
# BEGIN INIT INFO
# Provides:          hass
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Home\ Assistant
### END INIT INFO

PATH=$PATH:/usr/sbin/
HASS_BIN="/home/android/hass/bin/hass"
PID_FILE="/run/hass.pid"

CONFIG_DIR="/home/android/.homeassistant"
LOG_DIR="/var/log/homeassistant"
LOG_FILE="$LOG_DIR/home-assistant.log"
# FLAGS="-v --config $CONFIG_DIR --pid-file $PID_FILE --log-file $LOG_FILE --daemon"
FLAGS="-v --config $CONFIG_DIR --log-file $LOG_FILE "

# CMD="$PRE_EXEC; $HASS_BIN $FLAGS"

. /lib/lsb/init-functions

venv() {
    cd /home/android/hass
    . bin/activate
}

create_logdir() {
    if [ ! -d "$LOG_DIR" ]; then
        mkdir -p $LOG_DIR
        chown $RUN_AS "$LOG_DIR"
    fi
}


case "$1" in
    start)
        venv
        create_logdir
        # echo start-stop-daemon --start --pidfile $PID_FILE --exec $HASS_BIN -- $FLAGS 2>/dev/null
        start-stop-daemon --start --pidfile $PID_FILE --name hass --chuid android \
            --make-pidfile --background \
            --exec $HASS_BIN -- $FLAGS 2>/dev/null
        ;;
    stop)
        start-stop-daemon --stop --pidfile $PID_FILE --name hass --chuid android --retry=TERM/30/KILL/5 
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        # start-stop-daemon --status --pidfile $PID_FILE --name hass
        status_of_proc -p $PID_FILE hass "Home Assistant Service" && exit 0 || exit $?
        ;;
    logs)
        echo ">> log file: $LOG_FILE"
        tail -f $LOG_FILE && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|logs}"
        ;;
esac

exit 0
